language: php

compiler:
  - gcc

os:
  - linux
#  - osx

php:
  - 7.0
  - 7.1

notifications:
  email: hihozhou@gmail.com

before_install:
  - sudo apt-get -q update
install:
  # OpenCV dependencies - Details available at: http://docs.opencv.org/trunk/doc/tutorials/introduction/linux_install/linux_install.html
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install -y python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
  - cmake -version

  #- sudo apt-get install -y gcc-4.8 g++-4.8

  # Download OpenCV-contrib v3.3.0-rc
  - git clone https://github.com/opencv/opencv_contrib.git

  # Download OpenCV v3.3.0-rc
  - git clone https://github.com/opencv/opencv.git

  # Create a new 'build' folder.
  - mkdir build-opencv
  - cd build-opencv

  # Set build instructions for Ubuntu distro.
  - cmake  -D OPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules ..
  # Run 'make' with four threads.
  - make -j5

  # Install to OS.
  - sudo make install
  # Add configuration to OpenCV to tell it where the library files are located on the file system (/usr/local/lib)
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'

  - sudo ldconfig
  - echo "OpenCV installed."



#Compile
before_script:
    - ./travis/compile.sh

script:
    - exit 0